### ISSUE TITLE
use standard IP Lookup

### ISSUE THREAD

**Issue by sunnysideup** [Level51/silverstripe-recaptcha#3]
https://github.com/Level51/silverstripe-recaptcha/blob/dda6f4b744c4e9496d6edfd44aacd64eff431e96/code/RecaptchaField.php#L115

```php
    Controller::curr()->getRequest()->getIP();
````

to use the standard mechanism for getting the IP address?

**Comment by JZubero** [comment]
We had to implement that function because HTTPRequest's `getIP()` does not handle the `HTTP_X_CLUSTER_CLIENT_IP` header, which we've needed to get it working with our LoadBalancer setup at Rackspace. I will dig into this again and create a pull request.
